export const recommendedsList = [
    {
        id: '1',
        hotelImage: require('../assets/images/hotel/hotel_1.jpg'),
        hotelName: 'Luxus Hunza Attabad Lake Resort. ',
        rating: 5.0,
        place: 'Hunza',
        amount: 100,
    },
    {
        id: '2',
        hotelImage: require('../assets/images/hotel/hotel_2.jpg'),
        hotelName: 'Hotel Sunway Murree',
        rating: 5,
        place: 'Murree',
        amount: 50,
    },
    {
        id: '3',
        hotelImage: require('../assets/images/hotel/hotel_3.jpg'),
        hotelName: 'Pearl Continental Hotel, Muzaffarabad',
        rating: 5.0,
        place: 'Azad Kashmir',
        amount: 50,
    },
    {
        id: '4',
        hotelImage: require('../assets/images/hotel/hotel_4.jpg'),
        hotelName: 'Rose Palace Hotel, Gulberg',
        rating: 4.0,
        place: 'Lahore',
        amount: 50,
    },
    {
        id: '5',
        hotelImage: require('../assets/images/hotel/hotel_5.jpg'),
        hotelName: 'Islamabad Serena Hotel',
        rating: 5.0,
        place: 'Islamabad',
        amount: 200,
    },
];
